### ISSUE TITLE
serialize.cpp:189:8: error: '_' was not declared in this scope

### ISSUE THREAD

**Issue by itsme24** [eddelbuettel/rapiserialize#5]
Hi Dirk,

I get a compliation error on ubuntu with the latest version of RApiSerialize in line :
https://github.com/eddelbuettel/rapiserialize/blob/e9299b1d0ef9b707a22fd6b0d78b5e2027b46943/src/serialize.cpp#L189

see below:
![image](https://user-images.githubusercontent.com/31930324/186455428-9ee3dfee-27ea-446f-b3e6-d711c37a8a53.png)

could you please check the syntax, I think there are too many brackets and the underscore can vanish.

Many thanks.

**Comment by eddelbuettel** [comment]
Thanks for catching that.  The `_` is a macro for internationalization if and when one builds with it.  R does, which is why that line has it -- we don't so I should have removed it.

This passed all CI checks as it is in a conditional block TRUE for you but not elsewhere.  The local fix is 

```diff
modified   src/serialize.cpp
@@ -186,7 +186,7 @@ static SEXP CloseMemOutPStream(R_outpstream_t stream)
     /* duplicate check, for future proofing */
 #ifndef LONG_VECTOR_SUPPORT
     if(mb->count > INT_MAX)
-	error(_("serialization is too large to store in a raw vector"));
+	error("serialization is too large to store in a raw vector");
 #endif
     PROTECT(val = allocVector(RAWSXP, mb->count));
     memcpy(RAW(val), mb->buf, mb->count);

```

which I'll commit and likely send upstream to CRAN but the simple change should allow you to proceed now locally.

**Comment by itsme24** [comment]
Thanks for the prompt patch and comment, unfortunately I depend on the update of CRAN via second level package dependencies. The whole build process is not under my control, thus I would appreciate a CRAN update and cannot fix it locally for production Hope this is not too much work for you. Many thanks again

**Comment by eddelbuettel** [comment]
Release 0.1.2 just got onto CRAN so you should be good.  Thanks for the report!
